
# 1=as(in vocative ends with "-e" | 2=as(in vocative ends with "-ai" | 3=is(1st d) | 4=ys | 5=ias | 6=a | 7=ia | 8=ė | 9=is(F) | 10=is(M) | 11=us | 12=ius | 13=uo(M) | 14=uo(F)
nounList = [
    {"LT": "nam", "Ending": "as", "declension": 1, "LV": "māja", "EN": "house"},
    {"LT": "ąžuol", "Ending": "as", "declension": 1, "LV": "ozols", "EN": "oak"},
    {"LT": "vaik", "Ending": "as", "declension": 1, "LV": "bērns", "EN": "child"},
    {"LT": "snieg", "Ending": "as", "declension": 1, "LV": "sniegs", "EN": "snow"},
    {"LT": "žibint", "Ending": "as", "declension": 1, "LV": "laterna", "EN": "lantern"},
    {"LT": "lap", "Ending": "as", "declension": 1, "LV": "lapa", "EN": "leaf"},
    {"LT": "kard", "Ending": "as", "declension": 1, "LV": "zobens", "EN": "sword"},
    {"LT": "lank", "Ending": "as", "declension": 1, "LV": "loks", "EN": "bow"},
    {"LT": "skyd", "Ending": "as", "declension": 1, "LV": "vairogs", "EN": "shield"},
    {"LT": "moliūg", "Ending": "as", "declension": 1, "LV": "ķirbis", "EN": "pumpkin"},
    {"LT": "arbūz", "Ending": "as", "declension": 1, "LV": "arbūzs", "EN": "watermelon"},
    {"LT": "led", "Ending": "as", "declension": 1, "LV": "ledus", "EN": "ice"},
    {"LT": "blok", "Ending": "as", "declension": 1, "LV": "bloks", "EN": "block"},
    {"LT": "stikl", "Ending": "as", "declension": 1, "LV": "stikls", "EN": "glass"},
    {"LT": "vor", "Ending": "as", "declension": 1, "LV": "zirneklis", "EN": "spider"},
    {"LT": "gyvūn", "Ending": "as", "declension": 1, "LV": "dzīvnieks", "EN": "animal"},
    {"LT": "liūt", "Ending": "as", "declension": 1, "LV": "lauva", "EN": "lion"},
    {"LT": "vilk", "Ending": "as", "declension": 1, "LV": "vilks", "EN": "wolf"},
    {"LT": "šokolad", "Ending": "as", "declension": 1, "LV": "šokolāde", "EN": "chocolate"},
    {"LT": "padaž", "Ending": "as", "declension": 1, "LV": "mērce", "EN": "sauce"},
    {"LT": "apelsin", "Ending": "as", "declension": 1, "LV": "apelsīns", "EN": "orange"},
    {"LT": "pyrag", "Ending": "as", "declension": 1, "LV": "kūka", "EN": "cake"},
    {"LT": "banan", "Ending": "as", "declension": 1, "LV": "banāns", "EN": "banana"},
    {"LT": "berž", "Ending": "as", "declension": 1, "LV": "bērzs", "EN": "birch"},
    {"LT": "gryb", "Ending": "as", "declension": 1, "LV": "sēne", "EN": "mushroom"},
    {"LT": "žied", "Ending": "as", "declension": 1, "LV": "zieds", "EN": "flower"},
    {"LT": "sparn", "Ending": "as", "declension": 1, "LV": "spārns", "EN": "wing"},
    {"LT": "baln", "Ending": "as", "declension": 1, "LV": "segli", "EN": "saddle"},
    {"LT": "kastuv", "Ending": "as", "declension": 1, "LV": "lāpsta", "EN": "shovel"},
    {"LT": "buteliuk", "Ending": "as", "declension": 1, "LV": "pudele", "EN": "bottle"},
    {"LT": "kaul", "Ending": "as", "declension": 1, "LV": "kauls", "EN": "bone"},
    {"LT": "kibir", "Ending": "as", "declension": 1, "LV": "spainis", "EN": "bucket"},
    {"LT": "pien", "Ending": "as", "declension": 1, "LV": "piens", "EN": "milk"},
    {"LT": "skelet", "Ending": "as", "declension": 1, "LV": "skelets", "EN": "skeleton"},
    {"LT": "kompas", "Ending": "as", "declension": 1, "LV": "kompass", "EN": "compass"},
    {"LT": "delfin", "Ending": "as", "declension": 1, "LV": "delfīns", "EN": "dolphin"},
    {"LT": "abrikos", "Ending": "as", "declension": 1, "LV": "aprikots", "EN": "apricot"},
    {"LT": "aid", "Ending": "as", "declension": 1, "LV": "atbalss", "EN": "echo"},
    {"LT": "atvar", "Ending": "as", "declension": 1, "LV": "pūķis", "EN": "kite"},

    {"LT": "brol", "Ending": "is", "declension": 3, "LV": "brālis", "EN": "brother"},
    {"LT": "triuš", "Ending": "is", "declension": 3, "LV": "trusis", "EN": "rabbit"},
    {"LT": "draugel", "Ending": "is", "declension": 3, "LV": "taurenis", "EN": "butterfly"},
    {"LT": "sūr", "Ending": "is", "declension": 3, "LV": "siers", "EN": "cheese"},
    {"LT": "kiaušin", "Ending": "is", "declension": 3, "LV": "ola", "EN": "egg"},
    {"LT": "laikrod", "Ending": "is", "declension": 3, "LV": "pulkstens", "EN": "watch\" or \"clock"},
    {"LT": "kirv", "Ending": "is", "declension": 3, "LV": "cirvis", "EN": "axe"},
    {"LT": "med", "Ending": "is", "declension": 3, "LV": "koks", "EN": "tree"},

    {"LT": "arkl", "Ending": "ys", "declension": 4, "LV": "zirgs", "EN": "horse"},
    {"LT": "obuol", "Ending": "ys", "declension": 4, "LV": "ābols", "EN": "apple"},
    {"LT": "lok", "Ending": "ys", "declension": 4, "LV": "lācis", "EN": "bear"},
    {"LT": "vabzd", "Ending": "ys", "declension": 4, "LV": "kukainis", "EN": "insect"},
    {"LT": "kapl", "Ending": "ys", "declension": 4, "LV": "kaplis", "EN": "hoe"},
    {"LT": "dur", "Ending": "ys", "declension": 4, "LV": "durvis", "EN": "door"},
    {"LT": "šakn", "Ending": "ys", "declension": 4, "LV": "saknes", "EN": "root"},

    {"LT": "eln", "Ending": "ias", "declension": 5, "LV": "briedis", "EN": "deer"},

    {"LT": "duon", "Ending": "a", "declension": 6, "LV": "maize", "EN": "bread"},
    {"LT": "višt", "Ending": "a", "declension": 6, "LV": "vista", "EN": "chicken"},
    {"LT": "mės", "Ending": "a", "declension": 6, "LV": "gaļa", "EN": "meat"},
    {"LT": "pic", "Ending": "a", "declension": 6, "LV": "pica", "EN": "pizza"},
    {"LT": "citrin", "Ending": "a", "declension": 6, "LV": "citrons", "EN": "lemon"},
    {"LT": "uog", "Ending": "a", "declension": 6, "LV": "oga", "EN": "berry"},
    {"LT": "lov", "Ending": "a", "declension": 6, "LV": "gulta", "EN": "bed"},
    {"LT": "galv", "Ending": "a", "declension": 6, "LV": "galva", "EN": "head"},
    {"LT": "mork", "Ending": "a", "declension": 6, "LV": "burkāns", "EN": "carrot"},
    {"LT": "papūg", "Ending": "a", "declension": 6, "LV": "papagailis", "EN": "parrot"},
    {"LT": "sėkl", "Ending": "a", "declension": 6, "LV": "sēkla", "EN": "seed"},
    {"LT": "pluksn", "Ending": "a", "declension": 6, "LV": "spalva", "EN": "feather"},
    {"LT": "knyg", "Ending": "a", "declension": 6, "LV": "grāmata", "EN": "book"},
    {"LT": "lemp", "Ending": "a", "declension": 6, "LV": "lampa", "EN": "lamp"},
    {"LT": "rank", "Ending": "a", "declension": 6, "LV": "roka", "EN": "arm"},
    {"LT": "adaptacij", "Ending": "a", "declension": 6, "LV": "adaptācija", "EN": "adaption"},
    {"LT": "adat", "Ending": "a", "declension": 6, "LV": "adata", "EN": "needle\" or \"pin"},
    {"LT": "aguon", "Ending": "a", "declension": 6, "LV": "magone", "EN": "poppy"},

    {"LT": "skyrn", "Ending": "ia", "declension": 7, "LV": "lāde", "EN": "chest"},

    {"LT": "žem", "Ending": "ė", "declension": 8, "LV": "zeme", "EN": "earth\" or \"dirt"},
    {"LT": "karv", "Ending": "ė", "declension": 8, "LV": "govs", "EN": "cow"},
    {"LT": "kat", "Ending": "ė", "declension": 8, "LV": "kaķis", "EN": "cat"},
    {"LT": "kiaul", "Ending": "ė", "declension": 8, "LV": "cūka", "EN": "pig"},
    {"LT": "pel", "Ending": "ė", "declension": 8, "LV": "pele", "EN": "mouse"},
    {"LT": "bulv", "Ending": "ė", "declension": 8, "LV": "kartupelis", "EN": "potato"},
    {"LT": "kriauš", "Ending": "ė", "declension": 8, "LV": "bumbieris", "EN": "pear"},
    {"LT": "strėl", "Ending": "ė", "declension": 8, "LV": "bulta", "EN": "arrow"},
    {"LT": "egl", "Ending": "ė", "declension": 8, "LV": "egle", "EN": "spruce"},
    {"LT": "žvak", "Ending": "ė", "declension": 8, "LV": "svece", "EN": "candle"},
    {"LT": "mešker", "Ending": "ė", "declension": 8, "LV": "makšķere", "EN": "fishing rod"},
    {"LT": "žvaigžd", "Ending": "ė", "declension": 8, "LV": "zvaigzne", "EN": "star"},
    {"LT": "kepur", "Ending": "ė", "declension": 8, "LV": "cepure", "EN": "hat"},
    {"LT": "bit", "Ending": "ė", "declension": 8, "LV": "bite", "EN": "bee"},
    {"LT": "lap", "Ending": "ė", "declension": 8, "LV": "lapsa", "EN": "fox"},
    {"LT": "abėcėl", "Ending": "ė", "declension": 8, "LV": "alpfabēts", "EN": "alphabet"},

    {"LT": "žuv", "Ending": "is", "declension": 9, "LV": "zivs", "EN": "fish"},
    {"LT": "av", "Ending": "is", "declension": 9, "LV": "aita", "EN": "sheep"},

    {"LT": "cukur", "Ending": "us", "declension": 11, "LV": "cukurs", "EN": "sugar"},

    {"LT": "sensor", "Ending": "ius", "declension": 12, "LV": "sensors", "EN": "sensors"},
    {"LT": "popier", "Ending": "ius", "declension": 12, "LV": "papīrs", "EN": "paper"},

    {"LT": "akm", "Ending": "uo", "declension": 13, "LV": "akmens", "EN": "stone\" or \"rock"},
    {"LT": "asm", "Ending": "uo", "declension": 13, "LV": "persona", "EN": "person"},
    {"LT": "dub", "Ending": "uo", "declension": 13, "LV": "bļoda", "EN": "bowl"},
    {"LT": "lygm", "Ending": "uo", "declension": 13, "LV": "līmenis", "EN": "level"},]